import { spawnSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { homedir } from "node:os";
import type { DaemonServiceSpec } from "./service-spec.js";

/** Absolute path of the user unit for the label. */
export function systemdUnitPath(label: string): string {
  const configHome = process.env.XDG_CONFIG_HOME ?? path.join(homedir(), ".config");
  return path.join(configHome, "systemd", "user", `${label}.service`);
}

/**
 * Render the systemd user unit. Restart=on-failure, never always: `always` would
 * resurrect the daemon after `byspace daemon stop`, breaking stop semantics. The
 * supervisor's own crash restart handles worker failures. WantedBy=default.target
 * is the user-level equivalent of "start at login".
 */
export function renderSystemdUnit(spec: DaemonServiceSpec): string {
  const execStart = [spec.nodePath, spec.runnerEntry, ...spec.runnerArgs]
    .map((part) => part.replace(/([\\"])/g, "\\$1"))
    .join(" ");
  const envLines = Object.entries(spec.env)
    .map(([key, value]) => `Environment="${key}=${value.replace(/([\\"])/g, "\\$1")}"`)
    .join("\n");

  return `# Generated by 'byspace daemon install-service'. Edits are overwritten on reinstall.
[Unit]
Description=BySpace daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
ExecStart=${execStart}
${envLines}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
`;
}

function systemctl(args: string[]): { ok: boolean; output: string } {
  const result = spawnSync("systemctl", ["--user", ...args], {
    encoding: "utf8",
    timeout: 20_000,
  });
  const output = `${result.stdout ?? ""}${result.stderr ?? ""}`.trim();
  return { ok: result.status === 0, output };
}

/** Write the unit, reload the manager, and enable --now the service. */
export function installSystemdService(spec: DaemonServiceSpec): void {
  const unitPath = systemdUnitPath(spec.label);
  mkdirSync(path.dirname(unitPath), { recursive: true });
  writeFileSync(unitPath, renderSystemdUnit(spec), { mode: 0o644 });

  const daemonReload = systemctl(["daemon-reload"]);
  if (!daemonReload.ok) {
    throw new Error(`systemctl --user daemon-reload failed: ${daemonReload.output}`);
  }
  const enable = systemctl(["enable", "--now", `${spec.label}.service`]);
  if (!enable.ok) {
    throw new Error(`systemctl --user enable --now failed: ${enable.output}`);
  }
}

/** Stop, disable, and delete the unit. Idempotent. */
export function uninstallSystemdService(label: string): void {
  systemctl(["disable", "--now", `${label}.service`]);
  rmSync(systemdUnitPath(label), { force: true });
  systemctl(["daemon-reload"]);
}

/** MainPID from `systemctl --user show`, or null when the unit is not loaded. */
export function systemdServicePid(label: string): number | null {
  const { ok, output } = systemctl(["show", `${label}.service`, "--property", "MainPID"]);
  if (!ok) return null;
  const match = output.match(/^MainPID=(\d+)$/m);
  if (!match) return null;
  const pid = Number(match[1]);
  return pid > 0 ? pid : null;
}

/**
 * Whether the user lingers (user manager runs without an active login session).
 * Without lingering the service stops at logout — report it, never silently degrade.
 */
export function isLingerEnabled(user: string): boolean {
  const result = spawnSync("loginctl", ["show-user", user, "--property", "Linger"], {
    encoding: "utf8",
    timeout: 10_000,
  });
  return result.status === 0 && /Linger=yes/.test(result.stdout ?? "");
}
