/**
 * The replica's migration sequence, in multica's apply order.
 *
 * Order matters and is pinned by test against the source directory's lexical
 * rule — the runner stays dumb, the ordering contract lives here.
 *
 * Gaps are deliberate and documented: a source migration that only touches
 * the multitenancy circle (or a circle we cut wholesale, like IM channels,
 * GitHub, plugins, cloud usage metering) is skipped by the baseline's cut
 * list, and its number stays absent so the sequence stays diffable against
 * the source directory.
 */
import { migration001Init } from "./001-init.js";
import {
  migration003TaskContext,
  migration019InboxDetails,
  migration020TaskSession,
  migration028TaskTriggerComment,
  migration033Chat,
  migration093WebhookDeliveries,
  migration109AgentTaskWaitingLocalDirectory,
  migration110AutopilotTriggerEventFilters,
  migration117AgentTaskQueueInitiatorUserId,
  migration128AgentTaskQueueRuntimeMcpOverlay,
  migration132AgentTaskQueueRuntimeConnectedApps,
  migration158AgentTaskQueueChatInputTaskId,
  migration176WebhookDeliveryWorker,
  migration308AgentTaskBranchName,
  migration499AgentTaskIssueSnapshot,
  migration180TaskChatFinalizeDeferred,
  migration240AgentTaskRegenerateQuickActions,
  migration251AgentRuntimeUnbind,
  migration352AutopilotQuotaExecution,
  migration376AgentTaskDurableWorkDir,
  migration377ChannelChatContextGeneration,
  migration449AutopilotTriggerCreatedBy,
  migration451AgentTaskCommentThread,
  migration458AgentTaskCancellationActor,
  migration471CommentDeletedAt,
  migration531WakeupActorFilter,
} from "./residual-final.js";
import {
  migration021AgentInstructions,
  migration031AgentArchive,
  migration046AgentMcpConfig,
  migration060ChatSessionRuntimeId,
  migration095AgentThinkingLevel,
  migration404AgentStarterPrompts,
  migration432AgentConversationStartersRename,
} from "./residual-agent.js";
import {
  migration012InboxActor,
  migration091IssueStartDate,
  migration105IssueMetadata,
  migration348PluginViaAttribution,
  migration351IssueCommentRevision,
  migration360IssueLastActivityAt,
  migration444CommentRecoverySettledAt,
  migration470IssueStatusIcon,
  migration483IssueTriageState,
  migration490DropTriageStatusKeyReservation,
  migration536IssueDuplicateOf,
  migration537IssueDuplicateOfIndex,
  migration550CommentSuppressedAgents,
} from "./residual-audit.js";
import {
  migration040AgentCustomEnv,
  migration046AgentUniqueName,
  migration050AgentModel,
  migration050IssueFirstExecutedAt,
  migration055TaskLeaseAndRetry,
  migration058DropAutopilotPriorityAndProjectId,
  migration059LabelTimestamps,
  migration060AgentDescriptionLength,
  migration060IssueOriginQuickCreate,
  migration061TaskTriggerSummary,
  migration066ForceFreshSession,
  migration069CommentResolvedAt,
  migration079AutopilotRunSkippedStatus,
  migration085SquadArchive,
  migration086SquadAvatar,
  migration087SquadNameNotUnique,
  migration088SquadInstructions,
} from "./040-088.js";
import {
  migration120AutopilotSubscriber,
  migration122TaskHandoffNote,
  migration123IssueStage,
  migration124AutopilotRunPlannedAt,
  migration124TaskPrepareLease,
  migration128CommentRoutingEscalation,
  migration129AgentComposioAllowlistAndTaskOriginator,
  migration130AgentInvocationPermission,
  migration149IssueOriginAgentCreate,
  migration150AgentTaskCoalescedComments,
  migration157AgentTaskDeliveredComments,
  migration162ResourceLabels,
  migration163AgentBuilder,
  migration164AttachmentTaskId,
  migration166ProjectDates,
  migration184AgentTaskAttribution,
  migration185AgentTaskAccountableUser,
  migration186AutopilotRuleVersion,
  migration189AutopilotTriggerPublisher,
  migration190AgentTaskAttributionInvariantCheck,
  migration191IssueProperties,
  migration206AgentDisabledRuntimeSkills,
  migration212AgentServiceTier,
  migration224AgentTaskSessionRolloutMissing,
  migration234AgentTaskQueueRetiredSessionId,
  migration236AgentTaskQuickActionsDisabled,
  migration239CommentQuickAction,
  migration249IssueSubscriberDelegated,
  migration538TaskSupplement,
} from "./120-549.js";
import {
  migration090TaskIsLeader,
  migration096AutopilotSquadAssignee,
  migration127TaskSquadId,
  migration509IssueWakeup,
} from "./090-509.js";
import {
  migration084Squad,
  migration332IssueStatus,
  migration333IssueStatusPkeyIndex,
  migration334IssueStatusPrimaryKey,
  migration335IssueStatusWorkspaceKeyIndex,
  migration336IssueStatusWorkspaceNameIndex,
  migration337IssueStatusOpenCheck,
  migration338IssueStatusValidateFormat,
  migration339SeedIssueStatusCatalog,
} from "./084-339.js";
import {
  migration002AgentConfig,
  migration004AgentRuntimeLoop,
  migration008StructuredSkills,
  migration015IssueSubscriber,
  migration017CommentParentId,
  migration018CommentParentCascade,
  migration020IssueNumber,
  migration026CommentReactions,
  migration027IssueReactions,
  migration029Attachment,
  migration032DropAgentTriggers,
  migration034Projects,
  migration041AgentCustomArgs,
  migration042Autopilot,
} from "./002-042.js";
import type { Migration } from "./runner.js";

export const MIGRATIONS: readonly Migration[] = [
  migration001Init,
  migration002AgentConfig,
  migration003TaskContext,
  migration004AgentRuntimeLoop,
  migration008StructuredSkills,
  migration012InboxActor,
  migration015IssueSubscriber,
  migration017CommentParentId,
  migration018CommentParentCascade,
  migration019InboxDetails,
  migration020IssueNumber,
  migration020TaskSession,
  migration021AgentInstructions,
  migration026CommentReactions,
  migration027IssueReactions,
  migration028TaskTriggerComment,
  migration029Attachment,
  migration031AgentArchive,
  migration032DropAgentTriggers,
  migration033Chat,
  migration034Projects,
  migration040AgentCustomEnv,
  migration041AgentCustomArgs,
  migration042Autopilot,
  migration046AgentMcpConfig,
  migration046AgentUniqueName,
  migration050AgentModel,
  migration050IssueFirstExecutedAt,
  migration055TaskLeaseAndRetry,
  migration058DropAutopilotPriorityAndProjectId,
  migration059LabelTimestamps,
  migration060AgentDescriptionLength,
  migration060ChatSessionRuntimeId,
  migration060IssueOriginQuickCreate,
  migration061TaskTriggerSummary,
  migration066ForceFreshSession,
  migration069CommentResolvedAt,
  migration079AutopilotRunSkippedStatus,
  migration084Squad,
  migration085SquadArchive,
  migration086SquadAvatar,
  migration087SquadNameNotUnique,
  migration088SquadInstructions,
  migration090TaskIsLeader,
  migration091IssueStartDate,
  migration093WebhookDeliveries,
  migration095AgentThinkingLevel,
  migration096AutopilotSquadAssignee,
  migration105IssueMetadata,
  migration109AgentTaskWaitingLocalDirectory,
  migration110AutopilotTriggerEventFilters,
  migration117AgentTaskQueueInitiatorUserId,
  migration120AutopilotSubscriber,
  migration122TaskHandoffNote,
  migration123IssueStage,
  migration124AutopilotRunPlannedAt,
  migration124TaskPrepareLease,
  migration127TaskSquadId,
  migration128AgentTaskQueueRuntimeMcpOverlay,
  migration128CommentRoutingEscalation,
  migration129AgentComposioAllowlistAndTaskOriginator,
  migration130AgentInvocationPermission,
  migration132AgentTaskQueueRuntimeConnectedApps,
  migration149IssueOriginAgentCreate,
  migration150AgentTaskCoalescedComments,
  migration157AgentTaskDeliveredComments,
  migration158AgentTaskQueueChatInputTaskId,
  migration162ResourceLabels,
  migration163AgentBuilder,
  migration164AttachmentTaskId,
  migration166ProjectDates,
  migration176WebhookDeliveryWorker,
  migration180TaskChatFinalizeDeferred,
  migration184AgentTaskAttribution,
  migration185AgentTaskAccountableUser,
  migration186AutopilotRuleVersion,
  migration189AutopilotTriggerPublisher,
  migration190AgentTaskAttributionInvariantCheck,
  migration191IssueProperties,
  migration206AgentDisabledRuntimeSkills,
  migration212AgentServiceTier,
  migration224AgentTaskSessionRolloutMissing,
  migration234AgentTaskQueueRetiredSessionId,
  migration236AgentTaskQuickActionsDisabled,
  migration239CommentQuickAction,
  migration240AgentTaskRegenerateQuickActions,
  migration249IssueSubscriberDelegated,
  migration251AgentRuntimeUnbind,
  migration308AgentTaskBranchName,
  migration332IssueStatus,
  migration333IssueStatusPkeyIndex,
  migration334IssueStatusPrimaryKey,
  migration335IssueStatusWorkspaceKeyIndex,
  migration336IssueStatusWorkspaceNameIndex,
  migration337IssueStatusOpenCheck,
  migration338IssueStatusValidateFormat,
  migration339SeedIssueStatusCatalog,
  migration348PluginViaAttribution,
  migration351IssueCommentRevision,
  migration352AutopilotQuotaExecution,
  migration360IssueLastActivityAt,
  migration376AgentTaskDurableWorkDir,
  migration377ChannelChatContextGeneration,
  migration404AgentStarterPrompts,
  migration432AgentConversationStartersRename,
  migration444CommentRecoverySettledAt,
  migration449AutopilotTriggerCreatedBy,
  migration451AgentTaskCommentThread,
  migration458AgentTaskCancellationActor,
  migration470IssueStatusIcon,
  migration471CommentDeletedAt,
  migration483IssueTriageState,
  migration490DropTriageStatusKeyReservation,
  migration499AgentTaskIssueSnapshot,
  migration509IssueWakeup,
  migration531WakeupActorFilter,
  migration536IssueDuplicateOf,
  migration537IssueDuplicateOfIndex,
  migration538TaskSupplement,
  migration550CommentSuppressedAgents,
];
