import { createRequire } from "node:module";
import { describe, expect, it } from "vitest";

const require = createRequire(import.meta.url);
const withAndroidReleaseSigning = require("./with-android-release-signing.js");

const generatedBuildGradle = `plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bytetrue.byspace'
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
}
`;

describe("withAndroidReleaseSigning", () => {
  it("uses a dedicated release key when all credentials are present", () => {
    const result = withAndroidReleaseSigning.applyAndroidReleaseSigningGradle(generatedBuildGradle);

    expect(result).toContain("BYSPACE_REQUIRE_RELEASE_SIGNING");
    expect(result).toContain("storeFile file(byspaceAndroidKeystorePath)");
    expect(result).toContain(
      "signingConfig byspaceAndroidReleaseSigningConfigured ? signingConfigs.release : signingConfigs.debug",
    );
    expect(result.match(/@generated by with-android-release-signing/g)).toHaveLength(1);
  });

  it("is idempotent", () => {
    const once = withAndroidReleaseSigning.applyAndroidReleaseSigningGradle(generatedBuildGradle);
    expect(withAndroidReleaseSigning.applyAndroidReleaseSigningGradle(once)).toBe(once);
  });

  it("rejects an unexpected Gradle template", () => {
    expect(() =>
      withAndroidReleaseSigning.applyAndroidReleaseSigningGradle("android {\n}\n"),
    ).toThrow(/android block|signingConfigs/);
  });
});
